# Generated by Django 2.1.2 on 2018-12-27 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
